### ISSUE TITLE
hru's without hru_ids in GFV1_catchments_edited

### ISSUE THREAD

**Issue by jsadler2** [USGS-R/drb-network-prep#5]
Jake mentioned the need for universal ids in hru processing tasks (https://github.com/USGS-R/drb_gridmet_tools/pull/11#discussion_r837798165). I was looking into this for the gridmet data. In the `GFv1_catchments_edited.gpkg` file, there is an `hru_id` column which seems like would serve the purpose of more "universal" identifier. A couple questions I have about this:
1. Is this `hru_id_nat`? 

2. I noticed that for 6 of the 867 hru's, there is no `hru_id`. These are for the three segments that have been split (3_1/3_2, 51_1/51_2, 8_1/8_2). I'm wondering if we should still assign the original `hru_id` to the *_1 segments and maybe to the *_2 segments too.

**Comment by jzwart** [comment]
I think `hru_id` is region-specific ID.  pasting comment from PR here: 

Based on the data pull https://github.com/USGS-R/drb-network-prep/blob/940073e8d77c911b6fb9dc4e3657aeab1162a158/1_fetch.R#L32-L38 , looks like those `hru_id`'s are region-specific ID's - see metadata [here ](https://www.sciencebase.gov/catalog/file/get/535eda80e4b08e65d60fc834?f=__disk__12%2F3e%2F81%2F123e81778296aec8dc694697f4e106583aa21e6b&transform=1&allowOpen=true)and description below : 

>Features are indexed back to the NHDPlus dataset through the POI_ID attribute. POI_ID is identical to the NHDPlus COMI_ID attribute. Features are also given a Geospatial Fabric-specific identifier. These are seg_id and hru_id for segments and Hydrologic Response Units, respectively. seg_id and hru_id are unique within a Region. To resolve identity of a feature nationally with this Region-specific identifier, another attribute, region, must also be used. All feature identities have been confirmed as assigned.

I haven't looked into a cross-walk to the national ID, but it'd be named something like `hru_id_nat` or `hru_id_nhm` or `nhm_id` - see metadata [here ](https://www.sciencebase.gov/catalog/file/get/5e29d1a0e4b0a79317cf7f63?f=__disk__04%2Fd4%2F3b%2F04d43b67a2ea46be5cf3b856f676125bd9bfe312&transform=1&allowOpen=true)

**Comment by lekoenig** [comment]
> To resolve identity of a feature nationally with this Region-specific identifier, another attribute, region, must also be used.

Thanks for linking to the metadata, Jake. The description copied above was actually helpful in resolving some confusion I had with the national data, namely that values for `hru_segment` were repeated and not unique to the DRB (or region 02). This was one reason we originally opted to use the regional subset data. As Jake points out, we're currently downloading the regional subset of the GF v1.0, so `hru_id` refers to the regional HRU identifier (this attribute is called `hru_id_reg` or `hru_id_regional` in the national data). 

@jsadler2, re. your second question, do you mind providing a bit more detail as to how you think those values would be used (e.g., to link the derived catchments back to original polygons more readily; to have a unique identifier for each polygon in `p2_GFv1_catchments_edited_sf`; others?). 

For context, with these split segments we replaced the GF HRUs with new catchments obtained by dissolved NHDv2 catchment boundaries. I originally set `hru_id` as `NA` for these segments to 1) differentiate these segments as manually edited, and 2) because there's a many-to-one issue in that originally there may have been 2+ HRUs (with different values for `hru_id`) but now there is only one polygon in its place. I've included an image below to show what I mean for subsegid 3_1:

![new_map](https://user-images.githubusercontent.com/8785034/161993182-3036a607-abfe-4c32-a3e8-bc8d36ea5c1c.png)

So depending on the intended use case, we could either choose a value `hru_id_nat` for these derived catchments, or we could come up with a new unique value for the new polygon associated with subsegid 3_1.

**Comment by jzwart** [comment]
>your second question, do you mind providing a bit more detail as to how you think those values would be used 

Mostly for updating drivers and running PRMS-SNTemp models. The cutout for PRMS-SNTemp that we have runs on GF v1.0 and uses `hru_id_nat` as the identifiers. If there are missing HRUs in the PRMS-SNTemp model then it won't run, so accounting for all HRUs in that cutout is the goal. I did some manual matching [here ](https://code.usgs.gov/wma/wp/run-prms-sntemp/-/merge_requests/8#note_247370)(very quickly), and it'd be good to check with you all to see if this seems reasonable. 

Ideally, we'd use an updated geospatial fabric at some point (e.g. GF v2.0) so we don't have to modify the network and/or move away from using PRMS-SNTemp so we're less tied to models that need specific fabrics. Either way, I'd still advocate for including a more national identifier because that will help when scaling up to larger regions.
